tasks complited
Indyks/hh-school-2021-java-collections-stream pull request #1
Opened 2021-12-22 22:44 UTC by Indyks

Выполнены задания по Java, комментарии внутри коммита

2021-12-22 22:45 UTC, Indyks commented on src/tasks/Task1.java
> +Оценить асимптотику работы
Собственно, оценку асимптотики написал прямо в комментарии к коду задания

2021-12-22 22:48 UTC, Indyks commented on src/tasks/Task8.java
> -    if (persons.size() == 0) {
Нет смысла проверять входной список на количество элементов

2021-12-22 22:51 UTC, Indyks commented on src/tasks/Task8.java
>      persons.remove(0);
Не понятно зачем это нужно. Я посчитал, что если этот метод уже вызывается где-то в коде и работает, то убрав эту команду я могу заставить код заработать не так, как задумывалось
То есть здесь мы либо оставляем команду, либо рефакторим код и проверяем что везде, где этот метод вызывается всё работает правильно (надеюсь правильно употребил слово "рефакторим")
И да, далее таких моментов будет несколько, я буду просто писать в комментарии к таким местам: "Удаляем, либо рефакторим"

2021-12-22 22:52 UTC, Indyks commented on src/tasks/Task8.java
> +    return persons.stream()
Тут просто сделал чуть покрасивее в плане кодстайла

2021-12-22 22:53 UTC, Indyks commented on src/tasks/Task8.java
> +            .toList();
Заменил громоздкий старый вариант "collect(Collectors.toList())" на "toList()", смысл один и тот же

2021-12-22 22:54 UTC, Indyks commented on src/tasks/Task8.java
> +    return new HashSet<>(Task8.getNames(persons));
То же самое только без использования стрима

2021-12-22 22:55 UTC, Indyks commented on src/tasks/Task8.java
> -    return getNames(persons).stream().distinct().collect(Collectors.toSet());
И да, я заметил, что тут не нужен distinct() - собственно, idea даже сама подсветила это серым.
Не нужен он, поскольку далее мы собираем стрим в set, а там априори не может быть повторяющихся элементов

2021-12-22 22:57 UTC, Indyks commented on src/tasks/Task8.java
> -  //Не хотим выдывать апи нашу фальшивую персону, поэтому конвертим начиная со второй
Метод выдаёт по списку персон список имён этих персон

2021-12-22 22:59 UTC, Indyks commented on src/tasks/Task8.java
> -  //ну и различные имена тоже хочется
По списку персон Person формируем set String различных имён

2021-12-22 23:01 UTC, Indyks commented on src/tasks/Task8.java
> -  //Для фронтов выдадим полное имя, а то сами не могут
Для одной персоны Person выдаёт в строке "[Фамилия] [Имя]"

2021-12-22 23:02 UTC, Indyks commented on src/tasks/Task8.java
>    public String convertPersonToString(Person person) {
Не очень нравится название метода, я бы назвал, например "getFullName"
Но придётся рефакторить, либо оставлять

2021-12-22 23:04 UTC, Indyks commented on src/tasks/Task8.java
> -    if (person.getSecondName() != null) {
Не вижу смысла проверять на пустые имена

2021-12-22 23:04 UTC, Indyks commented on src/tasks/Task8.java
> -      result += " " + person.getSecondName();
Второй раз пытаемся втолкнуть фамилию, ОДНОГО РАЗА ДОСТАТОЧНО

2021-12-22 23:05 UTC, Indyks commented on src/tasks/Task8.java
> +    return person.getSecondName() + " " + person.getFirstName();
Всё в одну строку

2021-12-22 23:06 UTC, Indyks commented on src/tasks/Task8.java
> -    Map<Integer, String> map = new HashMap<>(1);
Убираем изначальный размер мапы, иначе она сама собой будет несколько лишних раз расширяться (скорее всего), скажется на производительности

2021-12-22 23:07 UTC, Indyks commented on src/tasks/Task8.java
> +        personNames.put(person.getId(), convertPersonToString(person));
Нет смысла проверять, есть ли в мапе уже такой ключ. Если он есть, то мы его просто перетрём

2021-12-22 23:07 UTC, Indyks commented on src/tasks/Task8.java
> +    return personNames;
Такое название переменной понятнее

2021-12-22 23:09 UTC, Indyks commented on src/tasks/Task8.java
> -  // словарь id персоны -> ее имя
Возвращаем мапу, где ключ - id персоны, а значение - её полное имя (фамилия + имя)

2021-12-22 23:10 UTC, Indyks commented on src/tasks/Task8.java
> -  // есть ли совпадающие в двух коллекциях персоны?
Совпадает ли в двух коллекциях хотя бы одна персона

2021-12-22 23:10 UTC, Indyks commented on src/tasks/Task8.java
> +            .anyMatch(person -> persons2.contains(person));
Сделал через стрим и .anyMatch, так код легче читается

2021-12-22 23:11 UTC, Indyks commented on src/tasks/Task8.java
>      count = 0;
Не понятно зачем здесь нарисовалась глобальная переменная, но если она здесь есть и всё работает, то
либо оставляем, либо рефакторим

2021-12-22 23:12 UTC, Indyks commented on src/tasks/Task8.java
>    public long countEven(Stream<Integer> numbers) {
Выдаёт количество четных значений в стриме

2021-12-22 23:13 UTC, Indyks commented on src/tasks/Task8.java
> +            .forEach(num -> count++);
Просто сделал чуть читабельнее по кодстайлу
Менять саму логику не стал, вроде оно работает. Хотя возможно есть более оптимальное решение

2021-12-22 23:14 UTC, Indyks commented on src/tasks/Task8.java
>  }
Еще одно - в зависимости от того, где находятся эти методы и как должны использоваться, возможно нужно поменять им модификатор доступа на private

2021-12-22 23:15 UTC, Indyks commented on src/tasks/Task6.java
>    private Set<String> getPersonDescriptions(Collection<Person> persons,
Чуть с ума не сошел с этой задачей

2021-12-25 08:36 UTC, genroelgvozo requested changes

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task1.java
> +Получается сложность - O(n) + сложность сортировки
получается O(n * сложность сортировки), а сортировка n log n это ОЧЕНЬ ДОЛГО, еще дольше чем бы ты просто перебором находил элемент

надо всего за O(n) - подготовить данные как-то, чтобы по айдишке быстро находить нужную персону

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task2.java
> +            .toList();
тут ок

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task3.java
> +            .toList();
ок

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task4.java
> +            .toList();
Task4::convert
а так ок

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task5.java
> +            .toList();
ок

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task5.java
> +            .toList();
но Task5 не надо писать, это же в этом классе же

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task6.java
>    private Set<String> getPersonDescriptions(Collection<Person> persons,
и получилось опять медленно
O(n*m) где n - кол-во ареек у персон, а m - кол-во ареек всего, а их очень много может быть, надо бы подготовить данные, чтобы нужную арейку находить быстро

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task7.java
> +            .collect(Collectors.toSet());
Vacancy::getTitle а так ок

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> -    if (persons.size() == 0) {
ЧАВО?
а remove(0) для пустого списка что будет?)

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
>      persons.remove(0);
такс, этот метод где-то используется ВОТ СЕЙЧАС В ДАННОМ ДЗ?)
что за отмазы в стиле "ну короче тут все зависит от чего-то, чего тут нет, поэтому делать ничего не буду"))
есть методы, предложили разобраться что они делают и написать то же самое (ну главную суть) но лучше

и этот метод надо править еще (а ты его еще и сломал, удалив if)

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> +            .toList();
разница все же есть, в чем она?

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return new HashSet<>(Task8.getNames(persons));
тут ок

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> -    if (person.getSecondName() != null) {
почему?

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return person.getSecondName() + " " + person.getFirstName();
Здравствуйте, null Олег!

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> +        personNames.put(person.getId(), convertPersonToString(person));
а ты не изменил поведение таким образом? важно ли это вообще?
и да, в мапу собрать короче и проще через стрим, не нужен цикл

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> +            .anyMatch(person -> persons2.contains(person));
стал ли он быстрее? за сколько выполняется исходный и твой код?

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
>      count = 0;
либо делаем, либо нет, 50 на 50
что это за выводы?)
у тебя она приватная, почему тебе надо думать вообще об этом?) ты публичный интерфейс если не меняешь, то как разница?)

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> +            .forEach(num -> count++);
не работает (не всегда)

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    boolean reviewerDrunk = true;
пока что обе false, нифига не EZ

2021-12-25 08:36 UTC, genroelgvozo commented on src/tasks/Task8.java
>  }
здесь никак принадлежность к классу не рассматривается, просто набор методов, написаных плохо (все), и надо поправить

2021-12-25 12:11 UTC, Indyks commented on src/tasks/Task8.java
> -    if (persons.size() == 0) {
Я почему-то был уверен, что remove(0) для пустого списка просто не отработает, но не выдаст out of bounds exception

2021-12-25 12:13 UTC, Indyks commented on src/tasks/Task8.java
>      persons.remove(0);
Почему отмазы-то? Я просто посмотрел на задачу со стороны поддержки какого-то крупного сервиса, если смотреть со стороны только домашки, то на данном этапе понимания этой строки я бы ее просто удалил
Буду думать еще

2021-12-25 12:22 UTC, Indyks commented on src/tasks/Task4.java
> +            .toList();
Да, так лучше

2021-12-25 12:27 UTC, Indyks commented on src/tasks/Task8.java
> +    boolean reviewerDrunk = true;
С первым еще постараюсь справиться, но вот со вторым есть проблемы!

2021-12-25 16:00 UTC, Indyks commented on src/tasks/Task8.java
> +    return person.getSecondName() + " " + person.getFirstName();
Можно просто null

2021-12-25 16:02 UTC, Indyks commented on src/tasks/Task8.java
>      count = 0;
Да, действительно не подумал, что она приватная. В следующей версии вынес её внутрь метода (сделал локальной)

2021-12-27 15:59 UTC, Indyks commented on src/tasks/Task1.java
> +            .collect(Collectors.toMap(Person::getId, person -> person));
Учёл замечание, подготовил данные, сделав словарь id -> Персона
Теперь гораздо быстрее

2021-12-27 16:01 UTC, Indyks commented on src/tasks/Task1.java
> +            .toList();
Тут O(n)

2021-12-27 16:02 UTC, Indyks commented on src/tasks/Task5.java
> +            .toList();
Да, точно. Убрал

2021-12-27 16:05 UTC, Indyks commented on src/tasks/Task6.java
> +            .collect(Collectors.toMap(Area::getId, area -> area));
Снова учёл замечания и сделал словарь id -> Area
По аналогии

2021-12-27 16:05 UTC, Indyks commented on src/tasks/Task7.java
> +            .collect(Collectors.toSet());
Есть такое

2021-12-27 16:07 UTC, Indyks commented on src/tasks/Task8.java
> +            .toList();
Додумался вместо отдельного persons.remove(0) с проверкой просто прописать в стриме skip(1) без проверки

2021-12-27 16:14 UTC, Indyks commented on src/tasks/Task8.java
> +            .toList();
Погуглил по поводу "collect(Collectors.toList())" и "toList()":
1. toList() возвращает неизменяемый список, в то время как collect(Collectors.toList()) может возвращать так же и изменяемый, в нашем случае это не важно, поскольку мы сразу ретёрним этот список
2. toList() использует внутри себя Stream.toArray(), выделяющий массив точной длины (если Spliterator имеет характеристику SIZED), а второй вариант всегда начинает с пустого ArrayList, накапливая в нём элементы. То есть имеем кроме того выигрыш по производительности

2021-12-27 16:15 UTC, Indyks commented on src/tasks/Task8.java
> -    if (person.getSecondName() != null) {
Потому что я null

2021-12-27 16:17 UTC, Indyks commented on src/tasks/Task8.java
> -      result += " " + person.getSecondName();
Нашёл в классе персон middleName, вернул на место
Вернул проверки на null и теперь еще учёл пробелы между словами, которые могли оказаться в начале fullName
Выглядит всё еще как........, не придумал как сделать красивее и без кучи if

2021-12-27 16:19 UTC, Indyks commented on src/tasks/Task8.java
> +      fullName += " " + person.getMiddleName();
Забыл тут убрать пробел, убрал в локальном репозитории

2021-12-27 16:22 UTC, Indyks commented on src/tasks/Task8.java
> +            .anyMatch(person -> persons2.contains(person));
Начальный вариант - O(n*m) - очень долго...

С AnyMatch выделить именно асимптотику не могу, но провёл тесты по времени, создав 100000 персон в обоих с списках и получил примерно одинаковый результат ~200мс (для наихудшего варианта, проверял через System.currentTimeMillis())
Получается тоже O(n*m)

2021-12-27 16:24 UTC, Indyks commented on src/tasks/Task8.java
> +    return numbers.filter(num -> (num % 2 == 0 && num != 0)).count();
Добавил проверку на ноль

2021-12-27 16:24 UTC, Indyks commented on src/tasks/Task8.java
>      boolean reviewerDrunk = false;
Надеюсь в этот раз угадал

2021-12-27 16:24 UTC, Indyks commented on src/tasks/Task8.java
> +    boolean codeSmellsGood = true;
Ну такое

2021-12-27 16:27 UTC, Indyks commented on src/tasks/Task8.java
> +            .anyMatch(person -> persons2.contains(person));
Не придумал как сделать быстрее

2021-12-27 16:32 UTC, Indyks commented on src/tasks/Task8.java
> +    return persons.stream().collect(Collectors.toMap(Person::getId, person -> getFullName(person)));
Тут учёл замечание и сделал через стрим

2021-12-27 16:34 UTC, Indyks commented on src/tasks/Task8.java
> +    return persons.stream().collect(Collectors.toMap(Person::getId, person -> getFullName(person)));
Поскольку айдишки у персон уникальные, проверка-таки не нужна и поведение не изменится

2021-12-28 06:54 UTC, genroelgvozo commented on src/tasks/Task8.java
> +            .toList();
хорошо, да. Ну и в целом .toList() всегда лучше, но как я упоминал что он только с 16 джавы, поэтому до некоторого момента его не было, и в проектах у нас не найдешь)

2021-12-28 06:56 UTC, genroelgvozo commented on src/tasks/Task8.java
> +            .anyMatch(person -> persons2.contains(person));
ну надо выделить асимптотику все таки, от чего она зависит то? (наихудший вариант это отсутствие одинаковых?)
Чтобы понять от чего зависит, можешь глянуть исходник Collections.disjoint 
но это уже на новогодние праздники, дз без этого зачту (короче c contains может быть быстрее, но не всегда)

2021-12-28 07:06 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return numbers.filter(num -> (num % 2 == 0 && num != 0)).count();
а 0 нечетное что ли?)

2021-12-28 07:07 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return persons.stream().collect(Collectors.toMap(Person::getId, person -> getFullName(person)));
((( 
ну передается же Collection 
айдишки уникальные, а в коллекции что, дубликатов быть не может?)

2021-12-28 07:10 UTC, genroelgvozo requested changes

2021-12-28 07:10 UTC, genroelgvozo commented on src/tasks/Task8.java
> +      fullName += " " + person.getMiddleName();
ааа, ты как думаешь, приятно такой код читать?)
понятно что его можно покрыть тестами и забыть, но хочется открыть метод и увидеть слова
"Берем эти три строки, фильтруем налл, и склеиваем через пробел" а не кучу ифов.. Хмм, а какое же АПИ позволяет вот так красиво описывать процесс 🤔 .. Кажется что-то было такое на лекции :trollface: 
 Я троллю, но понятно что для такой задачи как-то написать по другому это прям другая идеология, но попробуй заюзать стрим и Collectors.joining, увидишь как в три строчки это красиво сделать

2021-12-28 10:09 UTC, Indyks commented on src/tasks/Task8.java
> +            .collect(Collectors.joining(" "));
Как же это вкусно выглядит

2021-12-28 10:10 UTC, Indyks commented on src/tasks/Task8.java
> -      result += " " + person.getSecondName();
Прощай куча IF, здравствуй, Stream api

2021-12-28 10:11 UTC, Indyks commented on src/tasks/Task8.java
> +            .anyMatch(person -> persons2.contains(person));
Исходник гляну

2021-12-28 10:12 UTC, Indyks commented on src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
Гугл сказал, что ноль чётный. Сколько учусь, ни разу не сталкивался с мыслью, является ли ноль четным, это очень странно и... стыдно, что ли. Убрал проверку на ноль

2021-12-28 10:14 UTC, Indyks commented on src/tasks/Task8.java
> +            .collect(Collectors.toMap(Person::getId, person -> getFullName(person)));
Действительно, хоть айдишки и уникальные, коллекция может хранить повторяющиеся значения, поэтому добавил .distinct()

2021-12-28 10:45 UTC, Indyks commented on src/tasks/Task8.java
> +    return !Collections.disjoint(persons1, persons2);
Показалось что работает, запушил и проверил, не работает)))
Сделал git reset --hard и теперь гит не даёт запушить старую версию, сейчас разрулю

2021-12-29 12:20 UTC, genroelgvozo approved these changes

2022-08-26 11:54 UTC, closed without merging